ann_root: /net/acadia4a/data/zkhan/pathvqa
vqa_root: /net/acadia4a/data/zkhan/pathvqa/images
train_files: ['train']
dataset_name: pathvqa 
truncate_train_dataset_to: null

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
batch_size_train: 16 
batch_size_test: 16
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 2e-5

image_size: 480

k_test: 128
inference: 'rank'

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10

torch_home: /net/acadia10a/data/zkhan/torch_home
wandb: true